exports.Data = {
	"dates": {
		"Dec29": ["ps/p2", "hsb1"],
		"Dec28": ["ps/p1"],
		"Dec27": ["pvcm", "fbs/p5", "hsb1", "qlge"],
		"Dec26": ["fbs/p4", "ships"],
		"Dec25": ["fffi"],
		"Dec24": ["qftp/d19", "hsb1", "fbs/p3"],
		"Dec23": ["qftp/d18", "tse1/p2", "360hips"],
		"Dec20": ["360hips", "ships", "qftp/d17"],
		"Dec19": ["qftp/d16", "hsb1", "fff/p4"],
		"Dec18": ["fbs/p2", "tse1/p3"],
		"Dec17": ["fbs/p1", "tse1/p1"],
		"Dec16": ["fbtlva"],
		"Dec12": ["tse2/p5"],
		"Dec5": ["tse2/p4"],
		"Dec2": ["tse2/p3", "hsb1"],
		"Dec1": ["tse2/p2", "hsb1"],
		"Nov29": ["tse2/p1"],
		"Nov27": ["swm", "hsb1", "fff/p4"],
		"Nov26": ["tse1/p2", "fff/p2"],
		"Nov25": ["fbtlva"],
		"Nov21": ["tse1/p1", "swm"],
		"Nov20": ["hsb1"],
		"Nov19": ["tse1/p5"],
		"Nov18": ["fbtlva"],
		"Nov5": ["tse1/p4"],
		"Nov4": ["fbtlva"],
		"Oct31": ["tse1/p3"],
		"Oct29": ["tse1/p2"],
		"Oct25": ["tse1/p1"],
		"Oct24": ["tse1/p5"],
		"Oct23": ["bball"],
		"Oct22": ["tse1/p4"],
		"Oct21": ["fbtlva"],
		"Oct17": ["tse1/p3", "fff/p1"],
		"Oct16": ["tse1/p2"],
		"Oct15": ["tse1/p1"],
		"Oct9": ["tse1/p5", "fff/p4"]
	},
	"classes": {
		"hsb1": {"name": "Handstand Builder 1", "duration": 10, "color": "red"},
		"tse1/p1": {"name":"True Strength Evolution 1 - Part 1", "duration": 33, "color": "green"},
		"tse1/p2": {"name":"True Strength Evolution 1 - Part 2", "duration": 31, "color": "green"},
		"tse1/p3": {"name":"True Strength Evolution 1 - Part 3", "duration": 31, "color": "green"},
		"tse1/p4": {"name":"True Strength Evolution 1 - Part 4", "duration": 30, "color": "green"},
		"tse1/p5": {"name":"True Strength Evolution 1 - Part 5", "duration": 32, "color": "green"},
		"tse2/p1": {"name":"True Strength Evolution 2 - Part 1", "duration": 35, "color": "green"},
		"tse2/p2": {"name":"True Strength Evolution 2 - Part 2", "duration": 32, "color": "green"},
		"tse2/p3": {"name":"True Strength Evolution 2 - Part 3", "duration": 32, "color": "green"},
		"tse2/p4": {"name":"True Strength Evolution 2 - Part 4", "duration": 33, "color": "green"},
		"tse2/p5": {"name":"True Strength Evolution 2 - Part 5", "duration": 33, "color": "green"},
		"swm": {"name":"Shoulder & Wrist Mobility", "duration": 10},
		"fff/p1": {"name":"Fluid Flexibility Flows - Part 1", "duration": 33, "color": "gold"},
		"fff/p2": {"name":"Fluid Flexibility Flows - Part 2", "duration": 32, "color": "gold"},
		"fff/p3": {"name":"Fluid Flexibility Flows - Part 3", "duration": 48, "color": "gold"},
		"fff/p4": {"name":"Fluid Flexibility Flows - Part 4", "duration": 45, "color": "gold"},
		"fbs/p1": {"name":"Full Body Strength - Part 1", "duration": 31, "color": "olive"},
		"fbs/p2": {"name":"Full Body Strength - Part 2", "duration": 39, "color": "olive"},
		"fbs/p3": {"name":"Full Body Strength - Part 3", "duration": 34, "color": "olive"},
		"fbs/p4": {"name":"Full Body Strength - Part 4", "duration": 32, "color": "olive"},
		"fbs/p5": {"name":"Full Body Strength - Part 5", "duration": 36, "color": "olive"},
		"bball": {"name":"basketball", "duration": 60, "color": "brown"},
		"fbtlva": {"name":"fb tlv advanced club", "duration": 50, "color": "gold"},
		"ships": {"name":"Smarter Hips", "duration": 15, "color": "purple"},
		"fffi": {"name":"Fit Flow Fly Intermediate", "duration": 60, "color": "gold"},
		"pvcm": {"name":"Power Vinyasa Constant Movement", "duration": 40, "color": "gold"},
		"qlge": {"name":"Quickie Let Go Express", "duration": 18},
		"ps/p1": {"name":"Primal Strength - Part 1", "duration": 33, "color": "lightgreen"},
		"ps/p2": {"name":"Primal Strength - Part 2", "duration": 34, "color": "lightgreen"},
		"ps/p3": {"name":"Primal Strength - Part 3", "duration": 34, "color": "lightgreen"},
		"ps/p4": {"name":"Primal Strength - Part 4", "duration": 40, "color": "lightgreen"},
		"ps/p5": {"name":"Primal Strength - Part 5", "duration": 40, "color": "lightgreen"},
		"qftp": {"name": "Quest For The Press", "duration": 22},
		"360hips": {"name": "360 Hips", "duration": 26, "color": "purple"}
	}
};
